version: '3'
services:
  command-app:
    image: eduarandres/command-app:latest
    container_name: command-app
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: password
      MONGO_DB_URI: mongodb://root:password@mongo:27017/inventory?authSource=admin
      MONGO_DB_NAME: inventory
      RMQ_URI: amqp://root:password@rabbitmq:5672
    links:
      - mongo
      - rabbitmq
    volumes:
      - inventory-app:/command/app

  query-app:
    image: eduarandres/query-app:latest
    container_name: query-app
    ports:
      - 3001:3001
    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USER: root
      POSTGRES_DB_PASSWORD: password
      POSTGRES_DB_NAME: inventory
      RMQ_URI: amqp://root:password@rabbitmq:5672
    links:
      - postgres
      - rabbitmq
    volumes:
      - inventory-app:/query/app

  proxy-app:
    image: eduarandres/proxy-app:latest
    container_name: proxy-app
    ports:
      - 3002:3002
      - 81:81
    environment:
      RMQ_URI: amqp://root:password@rabbitmq:5672
    links:
      - rabbitmq
    volumes:
      - inventory-app:/proxy/app

  front-app:
    image: eduarandres/front-app:latest
    container_name: front-app
    restart: always
    ports:
      - 4200:4200
    environment:
      HOST_3000: http://command-app:3000
      HOST_3001: http://query:3001
      HOST_3002: http://proxy:3002
      HOST_81: http://proxy:81
    depends_on:
      - command-app
      - query-app
      - proxy-app
    volumes:
      - front-app:/usr/share/nginx/html

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    command:

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    volumes:
      - data-postgres:/data/db

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-data/data-mongo:/data/db

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./docker-data/data-rabbitmq:/var/lib/rabbitmq

volumes:
  data-postgres:
    name: data-postgres
    driver: local
  data-mongo:
    name: data-mongo
    driver: local
  data-rabbitmq:
    name: data-rabbitmq
    driver: local
  inventory-app:
    name: inventory-app
    driver: local
  front-app:
    name: front-app
    driver: local
